package com.driagon.services.configserver.mappers;

import com.driagon.services.configserver.dto.requests.CreateScopeRequest;
import com.driagon.services.configserver.dto.responses.CreateScopeResponse;
import com.driagon.services.configserver.dto.responses.ScopeResponse;
import com.driagon.services.configserver.entities.Scope;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.Mappings;

@Mapper(componentModel = "spring")
public interface ScopeMapper {

    @Mappings({
            @Mapping(target = "id", source = "id"),
            @Mapping(target = "scopeName", source = "name"),
            @Mapping(target = "description", source = "description"),
            @Mapping(target = "active", source = "active"),
            @Mapping(target = "createdBy", source = "createdBy.email"),
            @Mapping(target = "createdAt", source = "createdAt")
    })
    ScopeResponse mapScopeEntityToScopeResponse(Scope scope);

    @Mappings({
            @Mapping(target = "name", source = "scopeName"),
            @Mapping(target = "description", source = "description"),
            @Mapping(target = "active", constant = "true"),
            @Mapping(target = "accessKey", expression = "java(java.util.UUID.randomUUID().toString())"), // Generate a random UUID for accessKey
            @Mapping(target = "id", ignore = true) // ID will be generated by the database
    })
    Scope mapCreateScopeRequestToScopeEntity(CreateScopeRequest request);

    @Mappings({
            @Mapping(target = "id", source = "id"),
            @Mapping(target = "scopeName", source = "name"),
            @Mapping(target = "description", source = "description"),
            @Mapping(target = "accessKey", source = "accessKey"),
    })
    CreateScopeResponse mapScopeEntityToCreateScopeResponse(Scope scope);
}